
import './globals.css';
import "bootstrap/dist/css/bootstrap.min.css";
import Providers from '@/lib/Providers';
import ToastProvider from '@/lib/ToastProvider';



export const metadata = {
  title: 'Food Deliver',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Providers>
    <html lang="en">
      <body className='bg-globalBody'>
        <ToastProvider>
        {children}
        </ToastProvider>
        </body>
    </html>
    </Providers>
  )
}
