import { Inter } from 'next/font/google'
import './globals.css';
import "bootstrap/dist/css/bootstrap.min.css";



export const metadata = {
  title: 'Food Deliver',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-globalBody'>{children}</body>
    </html>
  )
}
